apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: dingtalk-service-receive
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/knative-sample/dingtalk-service:1.0